import type { CreativeQualityReport } from "./quality-check";

export const creativeStages = [
  "start",
  "brief",
  "directions",
  "studio",
  "approval",
  "client",
  "summary"
] as const;

export type CreativeStage = (typeof creativeStages)[number];

export const serviceTypes = [
  "single-static",
  "album-post",
  "motion-static",
  "resize",
  "ugc-video"
] as const;

export type ServiceType = (typeof serviceTypes)[number];

export function outputFormatForService(service: ServiceType): string {
  switch (service) {
    case "single-static":
      return "1:1 Static";
    case "album-post":
      return "Album post";
    case "motion-static":
      return "Motion static";
    case "resize":
      return "Resize";
    case "ugc-video":
      return "9:16 UGC";
  }
}

export function normalizeFormatBeatsForService(
  service: ServiceType | undefined,
  beats: readonly string[] | undefined
): readonly string[] {
  if (service === "single-static" || service === "resize") return [];
  return (beats ?? []).map((beat) => beat.trim()).filter(Boolean).slice(0, 3);
}
export const artworkModes = [
  "standard",
  "design-system",
  "reference-library"
] as const;
export type ArtworkMode = (typeof artworkModes)[number];
export const imagePromptModels = [
  "gpt-5.6-terra",
  "anthropic/claude-sonnet-4.6"
] as const;
export type ImagePromptModel = (typeof imagePromptModels)[number];
export const artworkOutputSizes = [
  "1024x1024",
  "1536x1024",
  "1024x1536",
  "2048x2048",
  "2048x1152",
  "3840x2160",
  "2160x3840"
] as const;
export type ArtworkOutputSize = (typeof artworkOutputSizes)[number];
export const defaultArtworkOutputSize: ArtworkOutputSize = "1024x1024";
export function artworkOutputSizeLabel(size: ArtworkOutputSize): string {
  switch (size) {
    case "1024x1024":
      return "1024x1024 (square)";
    case "1536x1024":
      return "1536x1024 (landscape)";
    case "1024x1536":
      return "1024x1536 (portrait)";
    case "2048x2048":
      return "2048x2048 (2K square)";
    case "2048x1152":
      return "2048x1152 (2K landscape)";
    case "3840x2160":
      return "3840x2160 (4K landscape)";
    case "2160x3840":
      return "2160x3840 (4K portrait)";
  }
}
export const angleExportGroups = ["recommended", "option"] as const;
export type AngleExportGroup = (typeof angleExportGroups)[number];
export const ctaActionTypes = [
  "website",
  "line",
  "phone",
  "form",
  "inbox",
  "store",
  "other"
] as const;
export type CtaActionType = (typeof ctaActionTypes)[number];
export type ReviewDecision = "approved" | "rejected" | null;
export type ClientReviewStatus = "queued" | "sent" | "revision" | "approved";

export interface CreativeBrief {
  service: ServiceType;
  quantity: number;
  text: string;
  attachments: readonly Attachment[];
}

export interface Attachment {
  id: string;
  name: string;
  mediaType: string;
  storageKey?: string;
}

export interface ReferenceImageSelection {
  id: string;
  url: string;
  label: string;
}

export const creativeMaterialRoles = [
  "main-object",
  "product",
  "supporting-component",
  "client-context"
] as const;
export type CreativeMaterialRole = (typeof creativeMaterialRoles)[number];

export interface UploadedCreativeMaterial {
  id: string;
  name: string;
  mediaType: string;
  role: CreativeMaterialRole;
  description: string;
  url: string;
  storagePath?: string;
  storageBucket?: string;
}

export interface CreativeDirection {
  id: string;
  /** Deliverable this direction was written for. Optional for saved legacy runs. */
  service?: ServiceType;
  /** Marks a hook entered by a user instead of generated by the Hook agent. */
  manual?: boolean;
  /** Short strategic category used by manually entered hooks. */
  pillar?: string;
  /** Review objective used by manually entered hooks. */
  objective?: string;
  hook: string;
  /** Concise supporting copy shown below the hook. Optional for saved legacy runs. */
  subheadline?: string;
  concept: string;
  /** Exact phrase inside the subheadline that should render bold. */
  subheadlineHighlight?: string;
  /** Review section used only when exporting the Angles PDF. */
  exportGroup?: AngleExportGroup | null;
  why: string;
  visual: string;
  cta: string;
  /** Short, verified facts that may support the caption or one artwork text block. */
  supportingPoints?: readonly string[];
  /** Format-native story beats. Album/UGC/video directions use exactly three. */
  formatBeats?: readonly string[];
  /** Intended conversion route for the CTA. Optional for saved legacy runs. */
  ctaActionType?: CtaActionType;
  /** Verified destination copied from brand context. Never generated from inference. */
  ctaDestination?: string;
  /** Reusable contact/footer line copied exactly from verified brand inputs or past posts. */
  contactLine?: string;
  caption: string;
  score?: number;
  selected: boolean;
}

export interface ApprovalGate {
  graphicDesign: ReviewDecision;
  clientService: ReviewDecision;
  projectManager: ReviewDecision;
}

export type ApprovalRole = keyof ApprovalGate;

export const emptyApprovalGate: ApprovalGate = {
  graphicDesign: null,
  clientService: null,
  projectManager: null
};

export type ApprovalComments = Record<ApprovalRole, string>;

export const emptyApprovalComments: ApprovalComments = {
  graphicDesign: "",
  clientService: "",
  projectManager: ""
};

export interface CreativeOutput {
  id: string;
  directionId: string;
  format: string;
  status: "draft" | "needs-revision" | "ready" | "fixed";
  clientStatus: ClientReviewStatus;
  assetUrl?: string;
  assetStoragePath?: string;
  assetBucket?: string;
  provider?: string;
  model?: string;
  revisionCount: number;
  approval: ApprovalGate;
  approvalComments: ApprovalComments;
  qaNote?: string;
  qaReport?: CreativeQualityReport;
  savedToReferences?: boolean;
}

export interface CreativeRun {
  id: string;
  brandId: string | null;
  stage: CreativeStage;
  artworkMode: ArtworkMode;
  imagePromptModel: ImagePromptModel;
  outputSize: ArtworkOutputSize;
  brief: CreativeBrief;
  directions: readonly CreativeDirection[];
  outputs: readonly CreativeOutput[];
  approval: ApprovalGate;
  createdAt: string;
  updatedAt: string;
}
